# Generated by Django 4.0.3 on 2022-03-31 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titel')),
                ('item1', models.CharField(blank=True, max_length=30, verbose_name='1')),
                ('preis1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis')),
                ('item2', models.CharField(blank=True, max_length=30, verbose_name='2')),
                ('preis2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis')),
                ('item3', models.CharField(blank=True, max_length=30, verbose_name='3')),
                ('preis3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis')),
                ('item4', models.CharField(blank=True, max_length=30, verbose_name='4')),
                ('preis4', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis')),
                ('item5', models.CharField(blank=True, max_length=30, verbose_name='5')),
                ('preis5', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
